// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Operating system details of the client.
public type OperatingSystem record {|
    # Operating system family name.
    string? family?;
    # Version of a client component.
    ClientVersion version?;
|};

# Represents the Queries record for the operation: getStream
public type GetStreamQueries record {
    # A location in the DataSet  that continues querying data
    string cursor?;
    # Maximum number of results to return
    int:Signed32 'limit?;
};

# Client information parsed from the user agent string of the event.
public type UserAgentClientInfo record {|
    # Operating system details of the client.
    OperatingSystem os?;
    # Browser details of the client.
    Browser browser?;
    # Device details of the client.
    Device device?;
|};

# Device details of the client.
public type Device record {|
    # Device model.
    string? model?;
    # Device family.
    string? family?;
    # Device brand.
    string? brand?;
|};

# Geographic location resolved from an IP address.
public type IpAddressLocation record {|
    # Country of the IP address.
    string? country?;
    # City of the IP address.
    string? city?;
    # Latitude of the IP address location.
    decimal? latitude?;
    # State or region of the IP address.
    string? state?;
    # Longitude of the IP address location.
    decimal? longitude?;
|};

# A page of monitoring events with the cursor for the next page.
public type StreamResponse record {|
    # List of monitoring events in the page.
    StreamingEvent[]? resultData?;
    # Cursor to pass in the next request to continue reading the stream.
    string? endCursor?;
|};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://account.docusign.com/oauth/token";
|};

# Version of a client component.
public type ClientVersion record {|
    # Patch version number.
    string? patch?;
    # Major version number.
    string? major?;
    # Minor version number.
    string? minor?;
|};

# A single monitoring event.
public type StreamingEvent record {|
    # Status of the proxy used for the request.
    string? proxyStatus?;
    # Country from which the event originated.
    string? country?;
    # Additional event-specific data.
    record {}? data?;
    # City from which the event originated.
    string? city?;
    # Latitude from which the event originated.
    decimal? latitude?;
    # Whether the affected user is a member of the domain.
    boolean? affectedUserIsMemberOfDomain?;
    # Source of the event.
    string? 'source?;
    # Client information parsed from the user agent string of the event.
    UserAgentClientInfo userAgentClientInfo?;
    # Identifier of the organization.
    string? organizationId?;
    # Result of the action.
    string? result?;
    # Browser used by the user.
    string? browser?;
    # Property affected by the event.
    string? property?;
    # Identifier of the referenced user.
    string? referencedUserId?;
    # Action that was performed.
    string? action?;
    # State or region from which the event originated.
    string? state?;
    # Whether the referenced user is a member of the domain.
    boolean? referencedUserIsMemberOfDomain?;
    # Time at which the event occurred.
    string timestamp?;
    # Longitude from which the event originated.
    decimal? longitude?;
    # Unique identifier of the event.
    string? eventId?;
    # Geographic location resolved from an IP address.
    IpAddressLocation ipAddressLocation?;
    # Operating system used by the user.
    string? os?;
    # Identifier of the affected user.
    string? affectedUserId?;
    # IP address from which the event originated.
    string? ipAddress?;
    # Type of proxy used for the request.
    string? proxyType?;
    # User agent string of the client.
    string? userAgent?;
    # Whether the user is a member of the domain.
    boolean? isUserMemberOfDomain?;
    # Identifier of the user who performed the action.
    string? userId?;
    # Identifier of the account.
    string? accountId?;
    # Site where the event occurred.
    string? site?;
    # Integrator key of the application that performed the action.
    string? integratorKey?;
    # Field affected by the event.
    string? 'field?;
    # Level of the proxy used for the request.
    string? proxyLevel?;
    # Device used by the user.
    string? device?;
    # Object affected by the event.
    string? 'object?;
|};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Browser details of the client.
public type Browser record {|
    # Browser family name.
    string? family?;
    # Version of a client component.
    ClientVersion version?;
|};
